### ISSUE TITLE
P29の表記

### ISSUE THREAD

**Issue by scapegoat06** [mlpnlp/mlpnlp#11]
p29の下の方にある
入力列全体(x<sub>1</sub>,x<sub>2</sub>・・・,T<sub>x</sub>)は
入力列全体(x<sub>1</sub>,x<sub>2</sub>・・・,x<sub>T<sub>x</sub></sub>)の誤りではないでしょうか？
（下付き文字はおそらく時刻なので）

**Comment by yuutat** [comment]
ありがとうございます。ご指摘の通りです。

![p29-inputseq-org](https://user-images.githubusercontent.com/1034551/28168766-1a22c3d4-681b-11e7-86c0-493fd41c9713.gif)
を
![p29-inputseq-new](https://user-images.githubusercontent.com/1034551/28168770-1ebaa290-681b-11e7-912f-849936df910c.gif)
に修正いたします。

**Comment by yuutat** [comment]
第4刷で修正予定です．ご報告ありがとうございました．
