### ISSUE TITLE
p.40の記述

### ISSUE THREAD

**Issue by tam17aki** [mlpnlp/mlpnlp#2]
「... この仮定を時間ごとに異なるパラメータを使うモデルに比べてパラメータ数が減り、...」とありますが、「この仮定を」よりも、「この仮定により」ぐらいが適当ではないでしょうか。ちょっと自信がありませんが。

**Comment by yuutat** [comment]
ご指摘ありがとうございます．「時間ごとに異なるパラメータを使うモデル」と「時間によらないパラメータを仮定するモデル」の対比なのでご指摘の通り「この仮定により」が適当でした．修正させていただきます．

**Comment by yuutat** [comment]
第3刷で修正予定です．ご報告ありがとうございました．
