### ISSUE TITLE
式(4.35)の数式

### ISSUE THREAD

**Issue by eiichiroi** [mlpnlp/mlpnlp#4]
式(4.35)が、

<img src="https://latex.codecogs.com/gif.latex?s(y)&space;=&space;f_{\theta}(\bold{x},&space;y)" title="s(y) = f_{\theta}(\bold{x}, y)" />

となっていますが、式(4.33)〜式(4.39)の一連の流れを見ると、

<img src="https://latex.codecogs.com/gif.latex?s(y)&space;=&space;\exp(f_{\theta}(\bold{x},&space;y))" title="s(y) = \exp(f_{\theta}(\bold{x}, y))" />

が正しそうです。

**Comment by eiichiroi** [comment]
失礼しました、式(4.35)ではなく、式(4.36)の方に指数関数が抜けている、が正しそうです。

<img src="https://latex.codecogs.com/gif.latex?Z(Y)&space;=&space;\sum_{\hat{y}&space;\in&space;Y}{\exp(s(\hat{y}))}" title="Z(Y) = \sum_{\hat{y} \in Y}{\exp(s(\hat{y}))}" />

**Comment by yuutat** [comment]
ご指摘の通り，式（4.36）に指数関数が抜けておりました．失礼いたしました．
修正いたします．

![softmax-eq-4 36-error](https://user-images.githubusercontent.com/1034551/26880211-a560831e-4bce-11e7-8df5-2de7ce99cc5c.png)
->

![softmax-eq-4 36](https://user-images.githubusercontent.com/1034551/26879398-e4c9ed18-4bcb-11e7-8056-e7515e70d779.png)

```latex
Z({\mathcal Y}) = \sum_{\tilde{y} \in {\mathcal Y}} \exp\left(s(\tilde{y})\right)
```

**Comment by yuutat** [comment]
第3刷で修正予定です．ご報告ありがとうございました．
