### ISSUE TITLE
式(4.4)と式(4.7)の列方向の連結

### ISSUE THREAD

**Issue by tomohideshibata** [mlpnlp/mlpnlp#5]
式(4.4)と式(4.7)の一番下ですが、最初の「本書で用いる記号」によれば、列方向の連結は「,」ではなく「;」ではないでしょうか。
(ざっと見た限り、列方向の連結はこの2ヵ所しかなさそうです。)

**Comment by unnonouno** [comment]
ご指摘のとおりです．ありがとうございます．

**Comment by unnonouno** [comment]
と思いましたが，ここは行方向の連結が正しいです．すいません．なので，表記に従うと縦に並べたもの，あるいはconcatが正しいです．

**Comment by tomohideshibata** [comment]
あ、そうですね。わかりました。

**Comment by yuutat** [comment]
ご指摘ありがとうございました。
式(4.4)は以下のように修正いたします。
![eq4 4org](https://user-images.githubusercontent.com/1034551/27506122-f070e5ee-58ec-11e7-94fd-bd74d222b4e5.gif)
-->
![eq4 4new-bmatrix](https://user-images.githubusercontent.com/1034551/27506033-d27c0660-58ea-11e7-9c69-abd7e886717b.gif) 
または
![eq4 4new-concat](https://user-images.githubusercontent.com/1034551/27506034-d6abdfda-58ea-11e7-9ac8-318a87174550.gif)

式(4.7)は以下のように修正いたします。
![eq4 7org](https://user-images.githubusercontent.com/1034551/27506127-fcf22724-58ec-11e7-9846-1c09a394b9f6.gif)
-->
![eq4 7new-bmatrix](https://user-images.githubusercontent.com/1034551/27506036-dfa2d06c-58ea-11e7-90ce-4ce1b8b10cb9.gif)
または
![eq4 7new-concat](https://user-images.githubusercontent.com/1034551/27506038-e667a5f8-58ea-11e7-96b2-db569981c29c.gif)

**Comment by yuutat** [comment]
第4刷で修正予定です．ご報告ありがとうございました．
