### ISSUE TITLE
P.92の最終段落の記述

### ISSUE THREAD

**Issue by tomohideshibata** [mlpnlp/mlpnlp#6]
「ほとんど最初の3単語のみの情報」とありますが、「ほとんど3番目の入力単語のみの情報」でしょうか。
より正確には「ほとんど3番目の入力単語の情報とh_j^{(t)}(で出力を決める...)」だと思いますが、それは明らかかもしれません。

**Comment by unnonouno** [comment]
気持ち的には隠れ層の情報だから前の単語の情報も入っているなぁと思ってこう書きましたが，文脈的には「ほとんど3番目の入力単語のみの情報」としたほうが意図が伝わりやすそうです．次の版で治そうと思います．ありがとうございます．

**Comment by tomohideshibata** [comment]
なるほど、わかりました。

**Comment by yuutat** [comment]
第4刷で修正予定です．ご報告ありがとうございました．
