### ISSUE TITLE
p.24末尾の微分係数に関する記述について

### ISSUE THREAD

**Issue by shirayu** [mlpnlp/mlpnlp#7]
p24末尾に，
「新しい関数の微分は以下のように<img src="https://latex.codecogs.com/gif.latex?f^{(1)}(h)" title="f^{(1)}(h)" />の微分に1を足したものになり必ず微分係数が1以上になります」
とありますが，
「<img src="https://latex.codecogs.com/gif.latex?f^{(1)}(h)" title="f^{(1)}(h)" />の微分」
が0以上になることは保証されているのでしょうか?

次のページで「<img src="https://latex.codecogs.com/gif.latex?w^{(1)}&plus;1" title="w^{(1)}+1" />は1に近い値になります」との記述との整合性が気になります．

**Comment by yuutat** [comment]
ありがとうございます。fの微分の絶対値が大きい場合には全体としても大きな値になるので、ご指摘のとおり正しい表現ではありませんでした。ここでは、通常では勾配消失が起きる場合を扱いたかったので、
> 必ず微分係数が1以上になります

は以下のように訂正させていただきます。
![p24-fl](https://user-images.githubusercontent.com/1034551/27505982-5df26b64-58e9-11e7-9802-a9c5ea5e1028.gif)の微分の絶対値が小さくても全体の微分係数は1に近い値になります

**Comment by yuutat** [comment]
第4刷で修正予定です．ご報告ありがとうございました．
