### ISSUE TITLE
p.10の式(2.5)について

### ISSUE THREAD

**Issue by himkt** [mlpnlp/mlpnlp#8]
第1刷のsoftmax関数の分母に

```\exp(o_y)```

とありますが，これは

```\exp(o_{\tilde{y}})```

ではないでしょうか？

**Comment by yuutat** [comment]
ご指摘ありがとうございます。おっしゃる通り、分母は全てのYで和を取っているため分子のyとは異なる記号を使うべきでした。

![eq2 5org](https://user-images.githubusercontent.com/1034551/28116924-302dbccc-6746-11e7-83e8-59bd2fca1456.gif)
を
![eq2 5new](https://user-images.githubusercontent.com/1034551/28116933-3484360c-6746-11e7-8911-4fd873f9c434.gif)
に修正いたします。

```tex
{\tt softmax} \left( \boldsymbol{o} \right)_y = \frac{\exp \left( o_y \right)}{\sum_{\tilde{y} \in {\cal Y}}\exp\left( o_{\tilde{y}} \right)}
```

**Comment by yuutat** [comment]
第4刷で修正予定です．ご報告ありがとうございました．
